### ISSUE TITLE
outdated docker-compose file

### ISSUE THREAD

**Issue by DanielRuf** [event-engine/php-inspectio-cody#2]
The dependencies now require PHP 8. But the current docker-compose file uses PHP 7.4: https://github.com/event-engine/php-inspectio-cody/blob/master/docker-compose.yml#L7

See also https://github.com/proophboard/php-cody-tutorial/issues/1

**Comment by DanielRuf** [comment]
After changing this to php8.0-cli, the next problem appears:

![grafik](https://user-images.githubusercontent.com/827205/227551807-52294154-6048-417a-9e35-79a5c5da4b27.png)

![grafik](https://user-images.githubusercontent.com/827205/227552480-a1ebd459-2af1-4d7b-ab9d-501358063f35.png)

The sed command seems to be not very reliable because it only references a line number, but this quickly breaks if some different code is at this place. I recommend using a better sed command.

![grafik](https://user-images.githubusercontent.com/827205/227553072-5791ee23-0eae-4a67-bac3-cce2d683ab02.png)

**Comment by DanielRuf** [comment]
The correct code of codyconfig.php would be now:

![grafik](https://user-images.githubusercontent.com/827205/227553625-f2874308-0849-4a3c-9b45-a0ce87c19748.png)

**Comment by codeliner** [comment]
Both issues should be fixed now. I followed your suggestion and improved the sed command ;)
